apiVersion: v1
kind: Service
metadata:
  name: quiz-ui-service
  namespace: quiz-namespace
spec:
  selector:
    app: quiz-ui
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
